[build]
  publish = "dist"
  command = "npm run build"
[build.processing.html]
<<<<<<< HEAD
  pretty_urls = true
=======
  pretty_urls = false
>>>>>>> origin/main
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"